"""new

Revision ID: d58f616eb29d
Revises: b14b54eb7c2a
Create Date: 2023-09-06 20:44:17.768409

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd58f616eb29d'
down_revision: Union[str, None] = 'b14b54eb7c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
